### ISSUE TITLE
pow(NaN,0) is 1, not NaN

### ISSUE THREAD

**Issue by LongTengDao** [LewisJEllis/nantalk#1]
BTW: I saw `#[fit]` in the doc, which seems like a markdown-extension syntax, which not supported in github, and I didn't see it before. What's that?

**Comment by LewisJEllis** [comment]
Fair point, the rule on `NaN ** anything = 1` comes in after the rule about `anything ** 0 = 1` :)
If I ever do this talk again, I'll make sure to update it.

The `#[fit]` bit is a directive for Deckset, the slides tool I used here. It makes text that wouldn't otherwise fill a slide scale up to fill the slide. Deckset has a few other extensions for more slide-oriented or formatting-oriented things like that that aren't standard markdown.
